//===-- EffOps.td - Python bindings for eff ---------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===---------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_EFF_OPS
#define PYTHON_BINDINGS_EFF_OPS

include "Eff/EffOps.td"

#endif
